@url = http://localhost:3000

POST {{url}}/email-response HTTP/1.1
Content-Type: application/json

{
    "clientEmail": "sparker@gmail.com",
    "prompt": "Hola, estoy interasado en adquirir sus servicios de ventas de bienes raices. Como puedo saber mas?"
}

###
GET {{url}}/email-response HTTP/1.1
Content-Type: application/json

###
GET {{url}}/email-response/1 HTTP/1.1
Content-Type: application/json

###
DELETE {{url}}/email-response/1 HTTP/1.1